feat: adds refactoring section
StyleLounge/style pull request #7
Opened 2018-04-06 11:18 UTC by brofori

2018-04-06 11:48 UTC, dpommeranz approved these changes

2018-07-05 12:56 UTC, reasn requested changes

2018-07-05 12:56 UTC, reasn commented on book/refactoring.md
> +# Refactoring
The article is not linked anywhere

2018-07-05 12:56 UTC, reasn commented on book/refactoring.md
> +> Stay disciplined when refactoring when following the approaches described in this article
All other articles use different bullet points

2018-07-05 12:56 UTC, reasn commented on book/refactoring.md
> +> ...
...

2018-07-05 12:56 UTC, reasn commented on book/refactoring.md
> +* [www.sitepoint.com/write-maintainable-javascript](https://www.sitepoint.com/write-maintainable-javascript/)
External links should come with an explanation

2018-07-05 13:02 UTC, reasn commented
Partly covered by https://guidelines.stylelounge.io/book/refactoring.html
Removed the external link because it's unrelated to the process of refactoring.

2018-07-05 13:02 UTC, closed without merging